#!/usr/bin/env python3
"""Derive GeneratedParams.h and truth.json for the iPlug2 fixture from ../groundtruth/spec.json.

Same answer key as the JUCE fixture; only framework-specific facts differ (product name, plugin
code, parameter-id scheme = index, resources embedded through the platform, no BinaryData names).
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
JUCE = HERE.parent / "groundtruth"
PRODUCT = "ABGroundTruthIP"
PLUGIN_CODE = "Abgi"


def main() -> int:
    spec = json.loads((JUCE / "spec.json").read_text(encoding="utf-8"))
    names = ["k" + p["id"][0].upper() + p["id"][1:] for p in spec["parameters"]]
    lines = ["// GENERATED by gen.py from ../groundtruth/spec.json — do not edit.", "#pragma once", "", "enum EParams", "{"]
    lines += [f"  {n}," for n in names] + ["  kNumParams", "};", "", "// Called from the constructor: same ids, names, ranges, defaults and units as the JUCE fixture.",
              "#define ABGT_INIT_PARAMS() \\"]
    for p, n in zip(spec["parameters"], names):
        if p["type"] == "bool":
            lines.append(f'  GetParam({n})->InitBool("{p["name"]}", {"true" if p["default"] else "false"}); \\')
        elif p["type"] == "choice":
            ch = ", ".join(f'"{c}"' for c in p["choices"])
            lines.append(f'  GetParam({n})->InitEnum("{p["name"]}", {p["default"]}, {{{ch}}}); \\')
        else:
            shape = f'new IParam::ShapePowCurve({1.0 / p["skew"]:.6f})' if abs(p["skew"] - 1.0) > 1e-6 else "IParam::ShapeLinear()"
            lines.append(f'  GetParam({n})->InitDouble("{p["name"]}", {p["default"]}, {p["min"]}, {p["max"]}, 0.001, "{p["units"]}", 0, "", {shape}); \\')
    lines[-1] = lines[-1].rstrip(" \\")
    lines += ["", "struct StateOnly { const char* id; float value; };",
              "static const StateOnly kStateOnly[] = { " + ", ".join(f'{{ "{f["id"]}", {f["value"]}f }}' for f in spec["state_only_fields"]) + " };", ""]
    (HERE / "GeneratedParams.h").write_text("\n".join(lines), encoding="utf-8")

    truth = {
        "product": PRODUCT, "company": spec["company"], "manufacturer_code": spec["manufacturer_code"], "plugin_code": PLUGIN_CODE, "version": spec["version"],
        "framework": "iPlug2",
        "parameters": [{
            "id": p["id"], "name": p["name"], "type": p["type"],
            "default": p["default"] if p["type"] != "choice" else p["choices"][p["default"]],
            "default_normalized": (1.0 if p["default"] else 0.0) if p["type"] == "bool" else (p["default"] / max(1, len(p["choices"]) - 1) if p["type"] == "choice" else None),
            "units": p.get("units", ""), "min": p.get("min"), "max": p.get("max"), "choices": p.get("choices"),
            "step_count": 1 if p["type"] == "bool" else (len(p["choices"]) - 1 if p["type"] == "choice" else 0),
            "tier": "VST3_EXPORTED_PARAMETER", "vst3_param_id": i,
        } for i, p in enumerate(spec["parameters"])],
        "state_fields": [{"id": p["id"], "tier": "VST3_EXPORTED_PARAMETER"} for p in spec["parameters"]] +
                        [{"id": f["id"], "tier": "STATE_SCHEMA_FIELD" if f["id"].startswith("waveShapers") else "UI_ONLY_CONTROL", "note": f["note"]} for f in spec["state_only_fields"]],
        "state_tree_type": None, "state_format": "iPlug2 IByteChunk (parameter values then state-only fields)",
        "classes": ["abgt::TptLowpass", "abgt::TanhShaper", "abgt::LicenseStub", "ABGroundTruthIP"],
        "dsp": spec["dsp"],
        "protected_subsystem": spec["protected_subsystem"],
        "resources": [{"binarydata_name": None, "platform_resource": r["name"], "file": "../groundtruth/" + r["file"],
                       "sha256": hashlib.sha256((JUCE / r["file"]).read_bytes()).hexdigest() if (JUCE / r["file"]).is_file() else None} for r in spec["resources"]],
        "buses": spec["buses"], "latency": spec["latency_samples"],
        "generated_from": "../groundtruth/spec.json", "spec_sha256": hashlib.sha256((JUCE / "spec.json").read_bytes()).hexdigest(),
        "not_applicable_gates": ["BinaryData names present", "no static key promoted to parameter (no embedded APVTS XML)"],
    }
    (HERE / "truth.json").write_text(json.dumps({"schema": "artifactbench.ground_truth", "schema_version": 1, "tool": "fixtures/groundtruth_iplug2/gen.py", "generated": "fixed", "data": truth}, indent=2) + "\n", encoding="utf-8")
    print(f"wrote GeneratedParams.h and truth.json ({len(truth['parameters'])} parameters, iPlug2 ids = indices)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
