// GENERATED by gen.py from ../groundtruth/spec.json — do not edit.
#pragma once

enum EParams
{
  kBypass,
  kMode,
  kInputGain,
  kCutoff,
  kDrive,
  kOversample,
  kOutputGain,
  kNumParams
};

// Called from the constructor: same ids, names, ranges, defaults and units as the JUCE fixture.
#define ABGT_INIT_PARAMS() \
  GetParam(kBypass)->InitBool("Bypass", false); \
  GetParam(kMode)->InitEnum("Mode", 1, {"Clean", "Warm", "Hot"}); \
  GetParam(kInputGain)->InitDouble("Input Gain", 0.0, -24.0, 24.0, 0.001, "dB", 0, "", IParam::ShapeLinear()); \
  GetParam(kCutoff)->InitDouble("Cutoff", 8000.0, 20.0, 20000.0, 0.001, "Hz", 0, "", new IParam::ShapePowCurve(3.333333)); \
  GetParam(kDrive)->InitDouble("Drive", 4.0, 1.0, 20.0, 0.001, "", 0, "", new IParam::ShapePowCurve(2.000000)); \
  GetParam(kOversample)->InitBool("Oversample", true); \
  GetParam(kOutputGain)->InitDouble("Output Gain", -6.0, -24.0, 24.0, 0.001, "dB", 0, "", IParam::ShapeLinear());

struct StateOnly { const char* id; float value; };
static const StateOnly kStateOnly[] = { { "waveShapers_0_1", 0.25f }, { "uiScale", 1.0f } };
