// GENERATED by gen.py from spec.json — do not edit.
#pragma once
#include <juce_audio_processors/juce_audio_processors.h>

namespace abus {
inline juce::AudioProcessorValueTreeState::ParameterLayout makeLayout()
{
    juce::AudioProcessorValueTreeState::ParameterLayout layout;
    layout.add (std::make_unique<juce::AudioParameterBool> (juce::ParameterID { "bypass", 1 }, "Bypass", false));
    layout.add (std::make_unique<juce::AudioParameterChoice> (juce::ParameterID { "mode", 1 }, "Shape", juce::StringArray { "Soft", "Hard" }, 0));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "trim", 1 }, "Trim", juce::NormalisableRange<float> (-12.0f, 12.0f, 0.0f, 1.0f), 0.0f, juce::AudioParameterFloatAttributes().withLabel ("dB")));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "tone", 1 }, "Tone", juce::NormalisableRange<float> (500.0f, 18000.0f, 0.0f, 0.4f), 12000.0f, juce::AudioParameterFloatAttributes().withLabel ("Hz")));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "amount", 1 }, "Amount", juce::NormalisableRange<float> (1.0f, 10.0f, 0.0f, 0.6f), 3.0f, juce::AudioParameterFloatAttributes().withLabel ("")));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "level", 1 }, "Level", juce::NormalisableRange<float> (-24.0f, 0.0f, 0.0f, 1.0f), -3.0f, juce::AudioParameterFloatAttributes().withLabel ("dB")));
    return layout;
}

struct StateOnly { const char* id; float value; };
inline const StateOnly kStateOnly[] = { { "curves_0_2", 0.5f }, { "lastTab", 2.0f } };
inline constexpr const char* kStateTreeType = "ABUNSEEN";
} // namespace abus
