"""Source generation for 04_reconstruction (SPEC §10, EXECUTE 4.2).

Writes, from the evidence model (``reconstruct.model``):

* ``human_source/``            concise idiomatic JUCE/C++ per module, evidence tags in comments
* ``evidence_source/``         decompiler pseudo-C for the DSP-role classes (copied from 01_evidence)
* ``Source/Active/``           ONLY what passed its gate: parameter layout (VERIFIED_RUNTIME ids),
                               processor/editor shell, and modules at ≥ BEHAVIORALLY_EQUIVALENT
* ``Source/RecoveredScaffolds/`` left as the static stage wrote them (not compiled)
* ``CMakeLists.txt``           FIDELITY | SURROGATE selected by the identity evidence
* ``07_agent_handoff/reconstruction_index.json``  statement-level provenance (symbol, file,
                               status, addresses, evidence, parameters, validation, rmse, todos)

Every generated value that is not VERIFIED or BEHAVIOR_MATCHED is tagged INFERRED or GENERATED
in the source and in the index. Nothing here bypasses or reimplements a PROTECTED_SUBSYSTEM.
"""

from __future__ import annotations

import hashlib
import json
import re
import shutil
from pathlib import Path
from typing import Any

from ab_engine.reconstruct import families
from ab_engine.reconstruct.model import ACTIVE_RMSE

HEADER = "// GENERATED by AB — Artifact Bench (reconstruction stage). Provenance: 07_agent_handoff/reconstruction_index.json\n"


def _f(v: float) -> str:
    return families._f(v)


def _ident(name: str) -> str:
    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return s if s and not s[0].isdigit() else f"P{s}"


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def surrogate_codes(product: str) -> tuple[str, str]:
    h = hashlib.sha256(product.encode("utf-8")).hexdigest()
    letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    return "AbSr", "S" + "".join(letters[int(h[i * 2:i * 2 + 2], 16) % len(letters)] for i in range(3))


# ---------------------------------------------------------------------------------------------
# Waveshaper module

def waveshaper_source(ws: dict[str, Any], params: list[dict[str, Any]]) -> str:
    fam = ws["family"]
    decl, expr = families.shape_body(fam, ws["params"])
    by_key = {p["key"]: p for p in params if p.get("generate")}
    lines = [HEADER, "#pragma once", "#include <cmath>", "#include <juce_audio_processors/juce_audio_processors.h>", "",
             f"// Waveshaper — BEHAVIOR_MATCHED {ws['rmse']:.3g} RMSE ({ws['classification_at_default']}) at the verified default,",
             f"// reference {ws['reference']} ({ws['curve_points']} points, x ∈ [{ws['x_range'][0]:.2f}, {ws['x_range'][1]:.2f}]).",
             f"// Family {fam}: {families.describe(fam)} — chosen by residual ({ws['family_basis']}).",
             "// Model: y = post · F (drive · pre · x). Parameter laws below were each measured one-at-a-time from the verified default;",
             "// their combination is INFERRED (separable). Statuses per law are in reconstruction_index.json.",
             "namespace ab_rebuild {", "struct Waveshaper", "{"]
    if decl:
        lines.append(decl.rstrip("\n"))
    lines += [f"    static constexpr float defaultDrive = {_f(ws['drive'])};",
              f"    static constexpr float defaultPost  = {_f(ws['post'])};",
              "    float pre = 1.0f, drive = defaultDrive, post = defaultPost;",
              "    bool passthrough = false, linear = false;",
              "    float linearSlope = 1.0f;", "",
              "    float process (float x) const noexcept",
              "    {",
              "        if (passthrough) return x;",
              "        if (linear) return linearSlope * x;",
              "        const float u = drive * pre * x;",
              "        juce::ignoreUnused (u);",
              f"        return post * ({expr});",
              "    }", "",
              "    // Per-block parameter application (the original smooths gains over ~20 ms — measured settle; INFERRED, not modelled).",
              "    void update (const juce::AudioProcessorValueTreeState& apvts) noexcept",
              "    {",
              "        pre = 1.0f; drive = defaultDrive; post = defaultPost; passthrough = false; linear = false; linearSlope = 1.0f;"]
    for mo in ws["modulation"]:
        p = by_key.get(mo["key"])
        if p is None:
            continue
        key = _cpp_str(mo["key"])
        law, knob = mo["law"], mo["knob"]
        tag = f"// {mo['status']} — {mo['law']}: {mo['basis']}"
        if law in ("none", "unmodeled"):
            lines.append(f"        // {mo['key']}: {tag[3:]}")
            continue
        lines.append(f"        {tag}")
        if law == "db":
            lines.append(f"        {knob} *= juce::Decibels::decibelsToGain (apvts.getRawParameterValue ({key})->load() - {_f(p['default'])});")
        elif law == "proportional":
            lines.append(f"        {knob} *= apvts.getRawParameterValue ({key})->load() / {_f(p['default'])};")
        elif law == "passthrough":
            lines.append(f"        if (apvts.getRawParameterValue ({key})->load() >= 0.5f) passthrough = true;")
        elif law == "passthrough_off":
            lines.append(f"        if (apvts.getRawParameterValue ({key})->load() < 0.5f) passthrough = true;")
        elif law == "discrete":
            var = f"v_{_ident(mo['key'])}"
            lines.append(f"        const int {var} = (int) std::lround (apvts.getRawParameterValue ({key})->load());")
            for r in mo["points"]:
                v = int(r.get("value", 0))
                if r.get("passthrough"):
                    lines.append(f"        if ({var} == {v}) passthrough = true;  // measured: identity")
                elif r.get("is_linear"):
                    lines.append(f"        if ({var} == {v}) {{ linear = true; linearSlope = {_f(r['linear']['slope'])}; }}  // measured: linear, RMSE {r['linear']['rmse']:.1e}")
                elif r["knob"] in ("pre", "drive", "post") and abs(r["factor"] - 1) > 5e-3:
                    lines.append(f"        if ({var} == {v}) {r['knob']} *= {_f(r['factor'])};  // measured factor, RMSE {r['rmse']:.1e}")
                else:
                    lines.append(f"        // {var} == {v}: default (no change measured)")
        elif law == "table":
            xs = ", ".join(_f(r["normalized"]) for r in mo["points"])
            fs = ", ".join(_f(r["factor"]) for r in mo["points"])
            ks = {r["knob"] for r in mo["points"] if r["knob"] in ("pre", "drive", "post")}
            k = next(iter(ks)) if len(ks) == 1 else "pre"
            lines.append(f"        {{ static const float xs[] = {{ {xs} }}; static const float fs[] = {{ {fs} }};")
            lines.append(f"          {k} *= interp (apvts.getParameter ({key})->getValue(), xs, fs, {len(mo['points'])}); }}  // INFERRED between the measured positions")
    lines += ["    }", "",
              "    static float interp (float n, const float* xs, const float* fs, int count) noexcept",
              "    {",
              "        if (count <= 0) return 1.0f;",
              "        if (n <= xs[0]) return fs[0];",
              "        for (int i = 1; i < count; ++i)",
              "            if (n <= xs[i]) { const float t = (n - xs[i - 1]) / (xs[i] - xs[i - 1]); return fs[i - 1] + t * (fs[i] - fs[i - 1]); }",
              "        return fs[count - 1];",
              "    }",
              "};", "} // namespace ab_rebuild", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------------
# parameter layout / processor / editor

def parameters_source(params: list[dict[str, Any]], state: dict[str, Any]) -> str:
    lines = [HEADER, "#pragma once", "#include <juce_audio_processors/juce_audio_processors.h>", "",
             "// Parameter layout — every row is a VST3_EXPORTED_PARAMETER seen by vst3host (VERIFIED_RUNTIME); ids reproduce the",
             "// original VST3 ParamIDs through juce::ParameterID{key, 1} (JUCE hashCode rule) where id_status says so.",
             "namespace ab_rebuild {",
             f"static constexpr const char* stateRootTag = {_cpp_str(state['root_tag'])};  // {state['root_status']}", "",
             "inline juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout()", "{",
             "    juce::AudioProcessorValueTreeState::ParameterLayout layout;"]
    for p in params:
        if not p.get("generate"):
            lines.append(f"    // {p.get('title')}: {p.get('note')}")
            continue
        pid = f"juce::ParameterID {{ {_cpp_str(p['key'])}, 1 }}"
        title = _cpp_str(p["title"])
        note = f"// {p['id_status']}"
        if p["kind"] == "bool":
            lines.append(f"    layout.add (std::make_unique<juce::AudioParameterBool> ({pid}, {title}, {'true' if p['default'] else 'false'}));  {note}; default VERIFIED_RUNTIME")
        elif p["kind"] == "choice":
            names = ", ".join(_cpp_str(c["name"]) for c in p["choices"])
            gen = [c["name"] for c in p["choices"] if c["status"].startswith("GENERATED")]
            lines.append(f"    layout.add (std::make_unique<juce::AudioParameterChoice> ({pid}, {title}, juce::StringArray {{ {names} }}, {p['default']}));  {note}; choice names {'VERIFIED_RUNTIME' if not gen else 'partly GENERATED: ' + ', '.join(gen)}")
        else:
            rng = f"juce::NormalisableRange<float> ({_f(p['min'])}, {_f(p['max'])}, 0.0f, {_f(p['skew'])})"
            attrs = f".withLabel ({_cpp_str(p['units'])})" if p.get("units") else ""
            lines.append(f"    layout.add (std::make_unique<juce::AudioParameterFloat> ({pid}, {title}, {rng}, {_f(p['default'])}, juce::AudioParameterFloatAttributes(){attrs}));  {note}; range {p['range_status']}")
    lines += ["    return layout;", "}", "} // namespace ab_rebuild", ""]
    return "\n".join(lines)


def processor_header(cls: str, product: str, m: dict[str, Any]) -> str:
    ident = m["identity"]
    lat = ident.get("latency_samples") or 0
    return f"""{HEADER}#pragma once
#include <juce_audio_processors/juce_audio_processors.h>
#include "Parameters.h"
{'#include "DSP/Waveshaper.h"' if m["modules"] and m["modules"][0]["active"] else '// Waveshaper module did not reach BEHAVIORALLY_EQUIVALENT: see human_source/ (not compiled)'}

class {cls} : public juce::AudioProcessor
{{
public:
    {cls}();
    ~{cls}() override = default;

    void prepareToPlay (double sampleRate, int maximumBlockSize) override;
    void releaseResources() override {{}}
    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;
    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;

    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override {{ return true; }}                          // VERIFIED_RUNTIME: original opens an editor ({(ident.get('editor') or {}).get('width')}×{(ident.get('editor') or {}).get('height')}); UI itself NOT recovered
    const juce::String getName() const override {{ return JucePlugin_Name; }}
    bool acceptsMidi() const override {{ return false; }}                       // VERIFIED_RUNTIME: no event input bus
    bool producesMidi() const override {{ return false; }}                      // VERIFIED_RUNTIME: no event output bus
    double getTailLengthSeconds() const override {{ return 0.0; }}              // VERIFIED_RUNTIME: tail {ident.get('tail_samples')} samples reported
    int getNumPrograms() override {{ return 1; }}
    int getCurrentProgram() override {{ return 0; }}
    void setCurrentProgram (int) override {{}}
    const juce::String getProgramName (int) override {{ return "Default"; }}    // VERIFIED_RUNTIME (IUnitInfo program list)
    void changeProgramName (int, const juce::String&) override {{}}
    void getStateInformation (juce::MemoryBlock&) override;
    void setStateInformation (const void*, int) override;

    juce::AudioProcessorValueTreeState apvts;

private:
    static constexpr int reportedLatency = {lat};   // VERIFIED_RUNTIME (getLatencySamples of the original); reproduced with a plain delay — cause (oversampling FIR) is a scaffold TODO
    {'ab_rebuild::Waveshaper shaper;' if m["modules"] and m["modules"][0]["active"] else ''}
    std::vector<std::vector<float>> delayBuf;
    std::vector<int> delayPos;
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR ({cls})
}};
"""


def processor_source(cls: str, editor_cls: str, m: dict[str, Any]) -> str:
    ident = m["identity"]
    buses = ident.get("buses") or {}
    n_in = (buses.get("input_audio") or [{}])[0].get("channel_count", 2) if buses.get("input_audio") else 2
    n_out = (buses.get("output_audio") or [{}])[0].get("channel_count", 2) if buses.get("output_audio") else 2
    bus_note = "VERIFIED_RUNTIME (IComponent::getBusInfo)" if buses else "GENERATED (stereo assumed; runtime bus info missing)"
    active = bool(m["modules"] and m["modules"][0]["active"])
    state_only = m["state"]["state_only"]
    so_lines = []
    for f in state_only:
        v = f["observed"]
        try:
            val = f"{float(v)!r}" if re.fullmatch(r"[-+]?\d+(\.\d+)?", v) else _cpp_str(v)
            if "." not in val and val.lstrip("-").isdigit():
                val = f"{val}.0"
        except ValueError:
            val = _cpp_str(v)
        so_lines.append(f"    state.setProperty ({_cpp_str(f['key'])}, {val}, nullptr);  // STATE_SCHEMA_FIELD, representation UNKNOWN, value observed at the factory default — INFERRED")
    process_body = (
        """    shaper.update (apvts);
    if (shaper.passthrough)
        return;  // measured: the bypassed original passes input through without the reported latency
    for (int ch = 0; ch < channels; ++ch)
    {
        auto* d = buffer.getWritePointer (ch);
        auto& ring = delayBuf[(size_t) ch];
        int& pos = delayPos[(size_t) ch];
        for (int i = 0; i < n; ++i)
        {
            const float y = shaper.process (d[i]);
            if (reportedLatency > 0) { const float out = ring[(size_t) pos]; ring[(size_t) pos] = y; pos = (pos + 1) % reportedLatency; d[i] = out; }
            else d[i] = y;
        }
    }"""
        if active else
        """    // No module reached BEHAVIORALLY_EQUIVALENT: the Active build is a verified shell (parameters, state, buses, latency) that passes audio through.
    juce::ignoreUnused (channels, n);""")
    return f"""{HEADER}#include "PluginProcessor.h"
#include "PluginEditor.h"

{cls}::{cls}()
    : AudioProcessor (BusesProperties()
                          .withInput ("Input", juce::AudioChannelSet::canonicalChannelSet ({n_in}), true)     // {bus_note}
                          .withOutput ("Output", juce::AudioChannelSet::canonicalChannelSet ({n_out}), true)),
      apvts (*this, nullptr, ab_rebuild::stateRootTag, ab_rebuild::createParameterLayout())
{{
    setLatencySamples (reportedLatency);
}}

bool {cls}::isBusesLayoutSupported (const BusesLayout& layouts) const
{{
    return layouts.getMainInputChannelSet() == juce::AudioChannelSet::canonicalChannelSet ({n_in})
        && layouts.getMainOutputChannelSet() == juce::AudioChannelSet::canonicalChannelSet ({n_out});
}}

void {cls}::prepareToPlay (double, int)
{{
    delayBuf.assign ((size_t) juce::jmax (1, getTotalNumOutputChannels()), std::vector<float> ((size_t) juce::jmax (1, reportedLatency), 0.0f));
    delayPos.assign (delayBuf.size(), 0);
}}

void {cls}::processBlock (juce::AudioBuffer<float>& buffer, juce::MidiBuffer&)
{{
    juce::ScopedNoDenormals noDenormals;
    const int channels = juce::jmin (buffer.getNumChannels(), (int) delayBuf.size());
    const int n = buffer.getNumSamples();
{process_body}
}}

// State: {m["state"]["format"]}; root tag {m["state"]["root_status"]}
void {cls}::getStateInformation (juce::MemoryBlock& dest)
{{
    auto state = apvts.copyState();
{chr(10).join(so_lines) if so_lines else "    // no state-only fields observed"}
    if (auto xml = state.createXml())
        copyXmlToBinary (*xml, dest);
}}

void {cls}::setStateInformation (const void* data, int size)
{{
    if (auto xml = getXmlFromBinary (data, size))
        if (xml->hasTagName (apvts.state.getType()))
            apvts.replaceState (juce::ValueTree::fromXml (*xml));
}}

juce::AudioProcessorEditor* {cls}::createEditor() {{ return new {editor_cls} (*this); }}
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter() {{ return new {cls}(); }}
"""


def editor_sources(cls: str, editor_cls: str, m: dict[str, Any]) -> tuple[str, str]:
    ed = (m["identity"].get("editor") or {})
    w, h = int(ed.get("width") or 520), int(ed.get("height") or 260)
    header = f"""{HEADER}#pragma once
#include "PluginProcessor.h"

// UI: NOT recovered (UI_ONLY_CONTROL evidence is absent). Generic parameter editor sized like the original ({w}×{h}, VERIFIED_RUNTIME).
class {editor_cls} : public juce::AudioProcessorEditor
{{
public:
    explicit {editor_cls} ({cls}& p) : juce::AudioProcessorEditor (p), generic (p) {{ addAndMakeVisible (generic); setSize ({w}, {h}); }}
    void resized() override {{ generic.setBounds (getLocalBounds()); }}
private:
    juce::GenericAudioProcessorEditor generic;
}};
"""
    source = f'{HEADER}#include "PluginEditor.h"\n'
    return header, source


def cmake_source(target: str, m: dict[str, Any], resources: list[str], product: str) -> str:
    ident = m["identity"]
    sur_m, sur_p = surrogate_codes(product)
    return f"""cmake_minimum_required(VERSION 3.22)
# GENERATED by AB — Artifact Bench. Build kinds (SPEC §10):
#   FIDELITY  — original identity from identity.cmake (VERIFIED_RUNTIME only). The only kind that can relink sessions.
#   SURROGATE — temporary generated identity so DSP work, pluginval and the differential harness can run. NEVER session-compatible.
project({target} VERSION 1.0.0 LANGUAGES C CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(AB_BUILD_KIND "{m['build_kind']}" CACHE STRING "SURROGATE or FIDELITY")

if(NOT DEFINED JUCE_DIR)
    set(JUCE_DIR "${{CMAKE_CURRENT_SOURCE_DIR}}/JUCE")   # git clone https://github.com/juce-framework/JUCE --branch 8.0.9, or -DJUCE_DIR=...
endif()
if(NOT EXISTS "${{JUCE_DIR}}/CMakeLists.txt")
    message(FATAL_ERROR "JUCE not found at ${{JUCE_DIR}}; pass -DJUCE_DIR=<path to JUCE 8.x>")
endif()
add_subdirectory("${{JUCE_DIR}}" JUCE EXCLUDE_FROM_ALL)

include(${{CMAKE_CURRENT_SOURCE_DIR}}/identity.cmake OPTIONAL)
if(AB_BUILD_KIND STREQUAL "FIDELITY")
    if(NOT DEFINED RECOVERED_MANUFACTURER_CODE OR NOT DEFINED RECOVERED_PLUGIN_CODE OR RECOVERED_MANUFACTURER_CODE STREQUAL "" OR RECOVERED_PLUGIN_CODE STREQUAL "")
        message(FATAL_ERROR "FIDELITY needs a VERIFIED_RUNTIME identity in identity.cmake (codes status: {ident.get('codes_status')}). Configure with -DAB_BUILD_KIND=SURROGATE.")
    endif()
    set(AB_COMPANY "${{RECOVERED_COMPANY}}")
    set(AB_PRODUCT "${{RECOVERED_PRODUCT}}")
    set(AB_MANUFACTURER_CODE ${{RECOVERED_MANUFACTURER_CODE}})
    set(AB_PLUGIN_CODE ${{RECOVERED_PLUGIN_CODE}})
    message(STATUS "AB FIDELITY build: ${{AB_COMPANY}} / ${{AB_PRODUCT}} (${{AB_MANUFACTURER_CODE}}/${{AB_PLUGIN_CODE}})")
else()
    set(AB_COMPANY "AB Surrogate")
    set(AB_PRODUCT "{product} AB-SURROGATE")
    set(AB_MANUFACTURER_CODE {sur_m})
    set(AB_PLUGIN_CODE {sur_p})
    message(WARNING "AB SURROGATE build: temporary identity {sur_m}/{sur_p}; this plugin cannot relink existing sessions or presets.")
endif()

juce_add_plugin({target}
    COMPANY_NAME "${{AB_COMPANY}}"
    PLUGIN_MANUFACTURER_CODE ${{AB_MANUFACTURER_CODE}}
    PLUGIN_CODE ${{AB_PLUGIN_CODE}}
    FORMATS VST3
    PRODUCT_NAME "${{AB_PRODUCT}}"
    IS_SYNTH FALSE
    NEEDS_MIDI_INPUT FALSE
    NEEDS_MIDI_OUTPUT FALSE
    COPY_PLUGIN_AFTER_BUILD FALSE
    VST3_CATEGORIES Fx)

{'juce_add_binary_data(' + target + 'Data SOURCES' + chr(10) + chr(10).join('    ' + r for r in resources) + ')' if resources else '# no recovered resources to embed'}

# Only Source/Active is compiled. Source/RecoveredScaffolds/ is evidence-derived scaffolding and is deliberately NOT in the build;
# a scaffold is promoted only once BEHAVIOR_MATCHED at ≥ BEHAVIORALLY_EQUIVALENT (07_agent_handoff/reconstruction_index.json).
target_sources({target} PRIVATE
    Source/Active/PluginProcessor.cpp
    Source/Active/PluginEditor.cpp)
target_include_directories({target} PRIVATE Source/Active)
target_compile_definitions({target} PUBLIC JUCE_WEB_BROWSER=0 JUCE_USE_CURL=0 JUCE_VST3_CAN_REPLACE_VST2=0 JUCE_DISPLAY_SPLASH_SCREEN=0)
target_link_libraries({target} PRIVATE {target + 'Data ' if resources else ''}juce::juce_audio_utils juce::juce_dsp
    PUBLIC juce::juce_recommended_config_flags juce::juce_recommended_warning_flags)
"""


# ---------------------------------------------------------------------------------------------

def _write(path: Path, text: str, written: list[str], root: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    written.append(path.relative_to(root).as_posix())


def generate(project: Path, m: dict[str, Any]) -> dict[str, Any]:
    """Write the reconstruction tree; return {index, written, target, summary}."""
    rec = project / "04_reconstruction"
    active = rec / "Source" / "Active"
    written: list[str] = []
    ident = m["identity"]
    product = ident.get("product") or project.name
    target = _ident(product) or "Rebuild"
    cls = f"{target}AudioProcessor"
    editor_cls = f"{target}AudioProcessorEditor"
    params = m["parameters"]
    index: list[dict[str, Any]] = []

    # ---- modules --------------------------------------------------------------------------
    for ws in m["modules"]:
        src = waveshaper_source(ws, params)
        _write(rec / "human_source" / "Waveshaper.h", src, written, project)
        if ws["active"]:
            _write(active / "DSP" / "Waveshaper.h", src, written, project)
        laws = [{"parameter": mo["key"], "law": mo["law"], "knob": mo["knob"], "status": mo["status"], "worst_rmse_ref": mo["worst_rmse_ref"], "basis": mo["basis"],
                 "points": [{k: r[k] for k in ("normalized", "knob", "factor", "rmse", "max_error") if k in r} | ({"value": r["value"]} if "value" in r else {}) | ({"linear_slope": r["linear"]["slope"]} if r.get("is_linear") else {})
                            for r in mo["points"]]} for mo in ws["modulation"]]
        index.append({"symbol": "ab_rebuild::Waveshaper", "role": ws["role"], "file": "04_reconstruction/human_source/Waveshaper.h",
                      "active_file": "04_reconstruction/Source/Active/DSP/Waveshaper.h" if ws["active"] else None, "compiled": ws["active"],
                      "status": ws["status"], "classification": ws["classification_at_default"], "rmse": ws["rmse"], "max_error": ws["max_error"], "correlation": ws["correlation"],
                      "family": ws["family"], "fit_params": ws["params"], "candidates": ws["candidates"], "family_basis": ws["family_basis"],
                      "evidence": ["BEHAVIOR_MATCHED (transfer curve, amplitude ramp, vst3host render of the original)", "VST3_EXPORTED_PARAMETER laws measured one-at-a-time"],
                      "reference": ws["reference"], "binary_addresses": [], "parameters": [mo["key"] for mo in ws["modulation"] if mo["law"] not in ("none", "unmodeled")],
                      "laws": laws, "validation": "PENDING (differential harness fills this in)",
                      "promotion": "Source/Active (fit ≤ 1e-4 RMSE = BEHAVIORALLY_EQUIVALENT gate)" if ws["active"] else f"human_source only: fit RMSE {ws['rmse']:.2e} > {ACTIVE_RMSE:g}",
                      "todos": [f"{mo['key']}: {mo['basis']}" for mo in ws["modulation"] if mo["law"] == "unmodeled"]
                      + ["combined parameter settings are INFERRED (separable model); extend probes to pairs to verify",
                         "parameter smoothing of the original (~20 ms measured settle) is not modelled"]})

    # ---- evidence_source (decompiler pseudo-C for DSP-role classes) -------------------------------
    ev_dir = rec / "evidence_source"
    dec_classes = project / "01_evidence" / "decompiler" / "classes"
    copied = 0
    if dec_classes.is_dir():
        for c in m["scaffolds"] + [{"safe": s.get("class", ""), "role": "DSP"} for s in m.get("dsp_functions", [])[:20]]:
            name = re.sub(r"[^A-Za-z0-9_]", "_", str(c.get("safe") or c.get("name") or ""))
            src = dec_classes / f"{name}.cpp"
            if name and src.is_file() and not (ev_dir / src.name).exists():
                ev_dir.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(src, ev_dir / src.name)
                written.append((ev_dir / src.name).relative_to(project).as_posix())
                copied += 1
    _write(ev_dir / "README.md", "# evidence_source\n\n" + (
        f"{copied} decompiler evidence file(s) copied from 01_evidence/decompiler/classes for the plugin-owned DSP-role classes. This is pseudo-C with binary addresses, kept close to decompiler semantics and never compiled; port into human_source/ only with evidence (reconstruction_index.json).\n"
        if copied else "No decompiler evidence is available for this job (DECOMPILATION_COMPLETE did not run or found no plugin-owned DSP classes). human_source/ modules are behaviour-fitted only.\n"), written, project)

    # ---- Active shell -------------------------------------------------------------------------
    _write(active / "Parameters.h", parameters_source(params, m["state"]), written, project)
    _write(active / "PluginProcessor.h", processor_header(cls, product, m), written, project)
    _write(active / "PluginProcessor.cpp", processor_source(cls, editor_cls, m), written, project)
    eh, es = editor_sources(cls, editor_cls, m)
    _write(active / "PluginEditor.h", eh, written, project)
    _write(active / "PluginEditor.cpp", es, written, project)
    for old in ("Source/Active/PluginProcessor.h", "Source/Active/PluginProcessor.cpp"):
        pass  # v2 files at the same paths are superseded above

    # ---- resources: resolved names first, carved names otherwise ------------------------------
    res_dir = rec / "Resources"
    resolved = None
    rp = project / "03_architecture" / "binarydata_resolved.json"
    if rp.is_file():
        resolved = json.loads(rp.read_text(encoding="utf-8")).get("data") or {}
    renames = (resolved or {}).get("renames") or {}
    resources: list[str] = []
    assets = project / "02_recovered_assets"
    if assets.is_dir():
        res_dir.mkdir(parents=True, exist_ok=True)
        for f in sorted(assets.rglob("*")):
            if f.is_file() and f.suffix.lower() in (".png", ".jpg", ".jpeg", ".svg", ".ttf", ".otf", ".xml", ".json", ".wav", ".aiff", ".txt"):
                name = renames.get(f.name, f.name)
                if name != f.name and f.name in renames.values():
                    continue  # already the resolved copy
                dst = res_dir / name
                if not dst.exists():
                    shutil.copyfile(f, dst)
                resources.append(f"Resources/{name}")
    resources = sorted(set(resources))
    _write(rec / "CMakeLists.txt", cmake_source(target, m, resources, product), written, project)
    if not (rec / "identity.cmake").is_file() and ident["verified"]:
        _write(rec / "identity.cmake", f'set(RECOVERED_COMPANY "{ident["vendor"]}")\nset(RECOVERED_PRODUCT "{product}")\nset(RECOVERED_MANUFACTURER_CODE "{ident["manufacturer_code"]}")\nset(RECOVERED_PLUGIN_CODE "{ident["plugin_code"]}")\n', written, project)
    _write(rec / ".gitignore", "build/\nJUCE/\n", written, project)

    # ---- index entries for the shell -----------------------------------------------------------
    index.append({"symbol": "ab_rebuild::createParameterLayout", "file": "04_reconstruction/Source/Active/Parameters.h", "compiled": True,
                  "status": "VERIFIED_RUNTIME" if all(p["id_status"].startswith("VERIFIED") for p in params if p.get("generate")) else "INFERRED",
                  "evidence": ["VST3_EXPORTED_PARAMETER (vst3host IEditController)", "state-differential key map", "5-point plain/display samples"],
                  "parameters": [{"key": p["key"], "param_id": p["param_id"], "kind": p["kind"], "id_status": p["id_status"], "range_status": p.get("range_status"),
                                  "default": p.get("default"), "units": p.get("units")} for p in params if p.get("generate")],
                  "todos": [f"{p['key']}: {p['range_status']}" for p in params if p.get("generate") and not str(p.get("range_status", "VERIFIED")).startswith("VERIFIED")]})
    index.append({"symbol": cls, "file": "04_reconstruction/Source/Active/PluginProcessor.cpp", "compiled": True, "status": "INFERRED",
                  "evidence": ["VERIFIED_RUNTIME buses/latency/tail/programs/editor size", "state root tag + state-only fields from the runtime state baseline"],
                  "parameters": [p["key"] for p in params if p.get("generate")],
                  "state": m["state"], "latency_samples": ident.get("latency_samples"),
                  "todos": ["latency is reproduced with a plain delay; the original's cause (oversampling filter) remains a scaffold",
                            "signal flow beyond the waveshaper (filter/oversampling) is not compiled; see RecoveredScaffolds"]})
    index.append({"symbol": editor_cls, "file": "04_reconstruction/Source/Active/PluginEditor.h", "compiled": True, "status": "GENERATED",
                  "evidence": ["VERIFIED_RUNTIME editor size"], "todos": ["UI not recovered: UI_ONLY_CONTROL evidence absent"]})
    for c in m["scaffolds"]:
        sub = "Protected" if c["role"] == "PROTECTED_SUBSYSTEM" else "UI" if c["role"] == "GUI" else "DSP" if c["role"] not in ("UNKNOWN", "STATE") else "Unclassified"
        index.append({"symbol": c["name"], "file": f"04_reconstruction/Source/RecoveredScaffolds/{sub}/{c['safe']}.h", "compiled": False, "status": "SCAFFOLD_ONLY",
                      "role": c["role"], "role_status": c["role_status"], "name_status": c["name_status"], "structure_status": c["structure_status"],
                      "binary_addresses": c.get("vtables", []) + c.get("methods", [])[:16], "bases": c.get("bases", []),
                      "evidence": ["RTTI"] + (["VERIFIED_VTABLE"] if c["structure_status"] == "VERIFIED_VTABLE" else []),
                      "promotion": "PROTECTED_SUBSYSTEM: map, never reimplement or bypass" if c["role"] == "PROTECTED_SUBSYSTEM" else "SCAFFOLD_ONLY → STATIC_RECONSTRUCTED → BEHAVIOR_MATCHED → Source/Active",
                      "todos": ["recover members/method bodies from evidence_source", "behavioural validation before promotion"] if c["role"] != "PROTECTED_SUBSYSTEM" else ["keep as an interface stub; licensing must not be reimplemented"]})
    summary = {"target": target, "build_kind": m["build_kind"], "modules_active": sum(1 for ws in m["modules"] if ws["active"]), "modules": len(m["modules"]),
               "parameters": sum(1 for p in params if p.get("generate")), "scaffolds": len(m["scaffolds"]), "resources": len(resources), "evidence_files": copied}
    return {"index": index, "written": written, "target": target, "summary": summary, "resources": resources}


__all__ = ["generate", "waveshaper_source", "parameters_source", "cmake_source", "surrogate_codes"]
