#!/usr/bin/env python3
"""Derive Source/GeneratedParams.h and truth.json from spec.json.

Run before building (build_all.* do it). truth.json is the answer key that
engine/ab_engine/groundtruth/compare.py scores a recovery bundle against.
"""
from __future__ import annotations

import hashlib
import json
import sys
import uuid
from pathlib import Path

HERE = Path(__file__).resolve().parent


def main() -> int:
    spec = json.loads((HERE / "spec.json").read_text(encoding="utf-8"))
    ns = spec["namespace"]
    lines = ["// GENERATED by gen.py from spec.json — do not edit.", "#pragma once", "#include <juce_audio_processors/juce_audio_processors.h>", "",
             f"namespace {ns} {{", "inline juce::AudioProcessorValueTreeState::ParameterLayout makeLayout()", "{",
             "    juce::AudioProcessorValueTreeState::ParameterLayout layout;"]
    for p in spec["parameters"]:
        if p["type"] == "bool":
            lines.append(f'    layout.add (std::make_unique<juce::AudioParameterBool> (juce::ParameterID {{ "{p["id"]}", 1 }}, "{p["name"]}", {"true" if p["default"] else "false"}));')
        elif p["type"] == "choice":
            choices = ", ".join(f'"{c}"' for c in p["choices"])
            lines.append(f'    layout.add (std::make_unique<juce::AudioParameterChoice> (juce::ParameterID {{ "{p["id"]}", 1 }}, "{p["name"]}", juce::StringArray {{ {choices} }}, {p["default"]}));')
        else:
            lines.append(f'    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID {{ "{p["id"]}", 1 }}, "{p["name"]}", juce::NormalisableRange<float> ({p["min"]}f, {p["max"]}f, 0.0f, {p["skew"]}f), {p["default"]}f, juce::AudioParameterFloatAttributes().withLabel ("{p["units"]}")));')
    lines += ["    return layout;", "}", "",
              "struct StateOnly { const char* id; float value; };",
              "inline const StateOnly kStateOnly[] = { " + ", ".join(f'{{ "{f["id"]}", {f["value"]}f }}' for f in spec["state_only_fields"]) + " };",
              f'inline constexpr const char* kStateTreeType = "{spec["state_tree_type"]}";',
              f"}} // namespace {ns}", ""]
    (HERE / "Source" / "GeneratedParams.h").write_text("\n".join(lines), encoding="utf-8")

    # truth.json: what a perfect recovery would report. JUCE derives the VST3 parameter
    # id from the string id (paramID hash) — recorded as the string; the runtime stage
    # compares titles/ids by string, numeric ParamIDs are captured live by vst3host.
    truth = {
        "product": spec["product"], "company": spec["company"], "manufacturer_code": spec["manufacturer_code"], "plugin_code": spec["plugin_code"], "version": spec["version"],
        "parameters": [{
            "id": p["id"], "name": p["name"], "type": p["type"],
            "default": p["default"] if p["type"] != "choice" else p["choices"][p["default"]],
            "default_normalized": (1.0 if p["default"] else 0.0) if p["type"] == "bool" else (p["default"] / max(1, len(p["choices"]) - 1) if p["type"] == "choice" else None),
            "units": p.get("units", ""), "min": p.get("min"), "max": p.get("max"), "choices": p.get("choices"),
            "step_count": 1 if p["type"] == "bool" else (len(p["choices"]) - 1 if p["type"] == "choice" else 0),
            "tier": "VST3_EXPORTED_PARAMETER",
        } for p in spec["parameters"]],
        "state_fields": [{"id": p["id"], "tier": "VST3_EXPORTED_PARAMETER"} for p in spec["parameters"]] +
                        [{"id": f["id"], "tier": "STATE_SCHEMA_FIELD" if f["id"].startswith("waveShapers") else "UI_ONLY_CONTROL", "note": f["note"]} for f in spec["state_only_fields"]],
        "state_tree_type": spec["state_tree_type"],
        "classes": spec["classes_expected"],
        "dsp": spec["dsp"],
        "protected_subsystem": spec["protected_subsystem"],
        "resources": [{"binarydata_name": r["name"], "file": r["file"], "sha256": hashlib.sha256((HERE / r["file"]).read_bytes()).hexdigest() if (HERE / r["file"]).is_file() else None} for r in spec["resources"]],
        "buses": spec["buses"], "latency": spec["latency_samples"],
        "generated_from": "spec.json", "spec_sha256": hashlib.sha256((HERE / "spec.json").read_bytes()).hexdigest(),
    }
    (HERE / "truth.json").write_text(json.dumps({"schema": "artifactbench.ground_truth", "schema_version": 1, "tool": "fixtures/groundtruth/gen.py", "generated": "fixed", "data": truth}, indent=2) + "\n", encoding="utf-8")
    void = uuid.uuid5(uuid.NAMESPACE_URL, spec["vst3_processor_uid_seed"])
    print(f"wrote Source/GeneratedParams.h and truth.json ({len(truth['parameters'])} parameters; uid seed {void})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
