"""MODERNIZE / REFACTOR generators (ADDENDUM C3): the transformed implementation of a fitted module.

The transformed module carries exactly the recovered math and parameter laws (they are re-used from the
reconstruction model, never re-derived here) behind current idioms: a block-processing API in the shape of
``juce::dsp::ProcessorBase`` (``prepare / process (context) / reset``), parameter handles cached once instead
of per-block string lookups, ``noexcept`` / ``[[nodiscard]]`` / ``constexpr`` laws, canonical names from the
identifier map. Whether that preserved behaviour is *measured*: the differential harness compares the
transformed build with the original and the graph records ``MODERNIZED_EQUIVALENT`` only on ≥
BEHAVIORALLY_EQUIVALENT.
"""

from __future__ import annotations

from typing import Any

from ab_engine.reconstruct import families

HEADER = "// Generated by AB (Artifact Bench) — transformed_source (ADDENDUM C3). Behaviour is the recovered model's; structure is modernized.\n"


def _f(v: float) -> str:
    s = f"{float(v):.9g}"
    if "e" in s or "." in s:
        return s + "f"
    return s + ".0f"


def _cpp_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ident(name: str) -> str:
    import re

    s = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return s if s and not s[0].isdigit() else f"P{s}"


def saturation_source(ws: dict[str, Any], params: list[dict[str, Any]], *, class_name: str = "SaturationStage", recovered_name: str = "ab_rebuild::Waveshaper") -> str:
    fam = ws["family"]
    decl, expr = families.shape_body(fam, ws["params"])
    by_key = {p["key"]: p for p in params if p.get("generate")}
    laws = [mo for mo in ws["modulation"] if mo["law"] not in ("none", "unmodeled") and mo["key"] in by_key]
    handles = sorted({mo["key"] for mo in laws})
    lines = [HEADER, "#pragma once", "#include <cmath>", "#include <array>", "#include <atomic>",
             "#include <juce_audio_processors/juce_audio_processors.h>", "#include <juce_dsp/juce_dsp.h>", "",
             f"// {class_name} — transformed from {recovered_name} (recovered_source/Waveshaper.h): family {fam}, {families.describe(fam)}.",
             f"// Fit {ws['rmse']:.3g} RMSE ({ws['classification_at_default']}) at the verified default; laws measured one-at-a-time (INFERRED separable).",
             "// Transformation: block-processing API (juce::dsp ProcessorBase shape), parameter handles cached at prepare(), noexcept /",
             "// [[nodiscard]] / constexpr — no intended behavioural change. Status is decided by the differential harness, not here.",
             "namespace ab_transformed {", f"class {class_name}", "{", "public:"]
    if decl:
        lines.append("    " + decl.strip().replace("\n", "\n    "))
    lines += [f"    static constexpr float defaultDrive = {_f(ws['drive'])};",
              f"    static constexpr float defaultPost  = {_f(ws['post'])};", "",
              "    /** Cache the parameter handles once (the recovered module looked them up by string every block). */",
              "    void prepare (const juce::AudioProcessorValueTreeState& apvts) noexcept",
              "    {"]
    for k in handles:
        lines.append(f"        h_{_ident(k)}.raw = apvts.getRawParameterValue ({_cpp_str(k)}); h_{_ident(k)}.param = apvts.getParameter ({_cpp_str(k)});")
    lines += ["        update();", "    }", "",
              "    void reset() noexcept {}", "",
              "    /** Per-block parameter application — the same laws as the recovered module. */",
              "    void update() noexcept",
              "    {",
              "        pre = 1.0f; drive = defaultDrive; post = defaultPost; passthrough = false; linear = false; linearSlope = 1.0f;"]
    for mo in laws:
        p = by_key[mo["key"]]
        h = f"h_{_ident(mo['key'])}"
        law, knob = mo["law"], mo["knob"]
        lines.append(f"        // {mo['status']} — {law}: {mo['basis']}")
        if law == "db":
            lines.append(f"        if ({h}.raw) {knob} *= juce::Decibels::decibelsToGain ({h}.raw->load() - {_f(p['default'])});")
        elif law == "proportional":
            lines.append(f"        if ({h}.raw) {knob} *= {h}.raw->load() / {_f(p['default'])};")
        elif law == "passthrough":
            lines.append(f"        if ({h}.raw && {h}.raw->load() >= 0.5f) passthrough = true;")
        elif law == "passthrough_off":
            lines.append(f"        if ({h}.raw && {h}.raw->load() < 0.5f) passthrough = true;")
        elif law == "discrete":
            var = f"v_{_ident(mo['key'])}"
            lines.append(f"        const int {var} = {h}.raw ? (int) std::lround ({h}.raw->load()) : 0;")
            for r in mo["points"]:
                v = int(r.get("value", 0))
                if r.get("passthrough"):
                    lines.append(f"        if ({var} == {v}) passthrough = true;  // measured: identity")
                elif r.get("is_linear"):
                    lines.append(f"        if ({var} == {v}) {{ linear = true; linearSlope = {_f(r['linear']['slope'])}; }}  // measured: linear")
                elif r["knob"] in ("pre", "drive", "post") and abs(r["factor"] - 1) > 5e-3:
                    lines.append(f"        if ({var} == {v}) {r['knob']} *= {_f(r['factor'])};  // measured factor")
        elif law == "table":
            xs = ", ".join(_f(r["normalized"]) for r in mo["points"])
            fs = ", ".join(_f(r["factor"]) for r in mo["points"])
            ks = {r["knob"] for r in mo["points"] if r["knob"] in ("pre", "drive", "post")}
            k = next(iter(ks)) if len(ks) == 1 else "pre"
            lines.append(f"        {{ static constexpr std::array<float, {len(mo['points'])}> xs {{ {xs} }}; static constexpr std::array<float, {len(mo['points'])}> fs {{ {fs} }};")
            lines.append(f"          if ({h}.param) {k} *= interp ({h}.param->getValue(), xs, fs); }}  // INFERRED between the measured positions")
    lines += ["    }", "",
              "    [[nodiscard]] bool isPassthrough() const noexcept { return passthrough; }", "",
              "    [[nodiscard]] float processSample (float x) const noexcept",
              "    {",
              "        if (passthrough) return x;",
              "        if (linear) return linearSlope * x;",
              "        const float u = drive * pre * x;",
              "        juce::ignoreUnused (u);",
              f"        return post * ({expr});",
              "    }", "",
              "    template <typename ProcessContext>",
              "    void process (const ProcessContext& context) noexcept",
              "    {",
              "        auto&& out = context.getOutputBlock();",
              "        const auto&& in = context.getInputBlock();",
              "        if (context.isBypassed || passthrough) { if (&in != &out) out.copyFrom (in); return; }",
              "        for (size_t ch = 0; ch < out.getNumChannels(); ++ch)",
              "        {",
              "            const float* src = in.getChannelPointer (ch);",
              "            float* dst = out.getChannelPointer (ch);",
              "            for (size_t i = 0; i < out.getNumSamples(); ++i)",
              "                dst[i] = processSample (src[i]);",
              "        }",
              "    }", "",
              "private:",
              "    struct Handle { std::atomic<float>* raw = nullptr; juce::RangedAudioParameter* param = nullptr; };"]
    for k in handles:
        lines.append(f"    Handle h_{_ident(k)};")
    lines += ["    float pre = 1.0f, drive = defaultDrive, post = defaultPost;",
              "    bool passthrough = false, linear = false;",
              "    float linearSlope = 1.0f;", "",
              "    template <size_t N>",
              "    static constexpr float interp (float n, const std::array<float, N>& xs, const std::array<float, N>& fs) noexcept",
              "    {",
              "        if (N == 0) return 1.0f;",
              "        if (n <= xs[0]) return fs[0];",
              "        for (size_t i = 1; i < N; ++i)",
              "            if (n <= xs[i]) { const float t = (n - xs[i - 1]) / (xs[i] - xs[i - 1]); return fs[i - 1] + t * (fs[i] - fs[i - 1]); }",
              "        return fs[N - 1];",
              "    }",
              "};", "} // namespace ab_transformed", ""]
    return "\n".join(lines)


__all__ = ["saturation_source", "HEADER"]
