// GENERATED by gen.py from spec.json — do not edit.
#pragma once
#include <juce_audio_processors/juce_audio_processors.h>

namespace abgt {
inline juce::AudioProcessorValueTreeState::ParameterLayout makeLayout()
{
    juce::AudioProcessorValueTreeState::ParameterLayout layout;
    layout.add (std::make_unique<juce::AudioParameterBool> (juce::ParameterID { "bypass", 1 }, "Bypass", false));
    layout.add (std::make_unique<juce::AudioParameterChoice> (juce::ParameterID { "mode", 1 }, "Mode", juce::StringArray { "Clean", "Warm", "Hot" }, 1));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "inputGain", 1 }, "Input Gain", juce::NormalisableRange<float> (-24.0f, 24.0f, 0.0f, 1.0f), 0.0f, juce::AudioParameterFloatAttributes().withLabel ("dB")));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "cutoff", 1 }, "Cutoff", juce::NormalisableRange<float> (20.0f, 20000.0f, 0.0f, 0.3f), 8000.0f, juce::AudioParameterFloatAttributes().withLabel ("Hz")));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "drive", 1 }, "Drive", juce::NormalisableRange<float> (1.0f, 20.0f, 0.0f, 0.5f), 4.0f, juce::AudioParameterFloatAttributes().withLabel ("")));
    layout.add (std::make_unique<juce::AudioParameterBool> (juce::ParameterID { "oversample", 1 }, "Oversample", true));
    layout.add (std::make_unique<juce::AudioParameterFloat> (juce::ParameterID { "outputGain", 1 }, "Output Gain", juce::NormalisableRange<float> (-24.0f, 24.0f, 0.0f, 1.0f), -6.0f, juce::AudioParameterFloatAttributes().withLabel ("dB")));
    return layout;
}

struct StateOnly { const char* id; float value; };
inline const StateOnly kStateOnly[] = { { "waveShapers_0_1", 0.25f }, { "uiScale", 1.0f } };
inline constexpr const char* kStateTreeType = "PARAMETERS";
} // namespace abgt
